### PR TITLE
Support Arduino Nano in `arduino-uno` crate

### PR DESCRIPTION
**Pull request by Rahix**
Implement support for Arduino Nano as proposed in issue #64.

### CODE REVIEW

**Comment by Rahix** [comment]
If someone with an Arduino Nano (**not** Arduino Nano Every) could give this a try (especially the ADC example), it would be much appreciated!  I can't really test whether ADC6 and ADC7 now work as intended ...

**Comment by kallemooo** [comment]
Tested una-adc.rs on an Arduino Nano.
All ADC channels works as expected.

One suggestion is to add in board documentation or uno-adc.rs how to build the example with the feature 'arduino-nano' enabled.

**Test build command:**
`cargo +nightly build --example uno-adc --features 'arduino-nano'`

**Test run command:**
`cargo +nightly run --example uno-adc --features 'arduino-nano'`

## Test 1
### Connected pins:
- ADC7 connected to 3.3 v
- ADC6 connected to 5.0 v
- ADC5 to ADC0 floating

### Serial output
`Vbandgap: 383`
`GND: 0`
`A0: 92 A1: 121 A2: 171 A3: 214 A4: 221 A5: 228 A6: 1023 A7: 696`
`A0: 565 A1: 468 A2: 423 A3: 406 A4: 360 A5: 331 A6: 1023 A7: 697` 
`A0: 588 A1: 497 A2: 446 A3: 422 A4: 374 A5: 340 A6: 1022 A7: 696`

## Test 2
### Connected pins:
- ADC7 connected to GND
- ADC6 connected to 3.3 v
- ADC5 to ADC0 floating

### Serial output
`Vbandgap: 344`
`GND: 0`
`A0: 83 A1: 80 A2: 111 A3: 165 A4: 186 A5: 191 A6: 695 A7: 0`
`A0: 67 A1: 102 A2: 152 A3: 189 A4: 197 A5: 200 A6: 697 A7: 0`
`A0: 70 A1: 106 A2: 158 A3: 197 A4: 210 A5: 217 A6: 695 A7: 0`

**Comment by Rahix** [comment]
@kallemooo, thanks so much! That's exactly what I was looking for.

**Comment by tippfehlr** [comment]
Sorry to bump this old issue.
Would it be possible/Why aren’t A6/7 accessed the way all the other pins are accessed? I guess that `pins` is general and `extra-adc-pins` only enables `arduino-hal::adc`?

**Comment by Rahix** [comment]
The reason is that these pins are not "normal".  They can only be used for the ADC and do not support GPIO modes like all other pins.  Thus we cannot simply reuse the existing port/pin code and need a different mechanism...

**Pull request merged**
