### PR TITLE
Add ATtiny167 support and ADC support for all ATtiny chips

### PR DESCRIPTION
**Pull request by quentinmit**
Part two of #202 (includes the commit from #203)

### CODE REVIEW

**Comment by quentinmit** [comment]
It looks like this is going to need a release of `avr-device` before it can pass CI.

**Comment by Rahix** [comment]
Yeah, I'll hopefully get around to that later this week.  In the meantime, you can of course use a cargo dependency patch to use the git version instead.

**Comment by Rahix** [comment]
BTW, with #203 merged, can you please rebase this PR branch on `main` now?

**Comment by quentinmit** [comment]
Rebased. Are you saying you want me to include a dependency patch in this PR? I assumed you wouldn't be willing to merge that.

**Comment by Rahix** [comment]
> Are you saying you want me to include a dependency patch in this PR?

No, just wanted to mention it for your local adventures with the code.  But I suppose you're most likely doing that already, anyway :)

**Review by Rahix — APPROVED** [review]
Okay, sorry for completely loosing track of this PR.  I rebased it on latest `main`, CI is passing so I'll merge it now.  Thanks for your work here, I appreciate the contributions a lot.  Just being a bit slow to get them all sorted out, sorry...

**Pull request merged**
