### PR TITLE
Fixes for pro micro

### PR DESCRIPTION
**Pull request by cecton**
> I also realized that I might have added too many pins. i.e. there are no pin A4 and A5 that I can see on the board! I probably made a mistake.

If there is no pin but there is still ACD1 and ACD0 on the schematics. Does that mean it still have a use? (For the alternate function --~~I'm not sure what's the alternate function~~ ok I think I know--) Then, should we keep them anyway?

### CODE REVIEW

**Comment by cecton** [comment]
(I'm not sure if the failing example is valid on the pro micro. It seems it lacks the necessary pins)

**Comment by Rahix** [comment]
> (I'm not sure if the failing example is valid on the pro micro. It seems it lacks the necessary pins)

If the pro micro has an onboard LED you should use that pin instead.  If not, any pin you like will do ...

**Comment by Rahix** [comment]
Can you do this change so I can merge the PR? :)

**Comment by cecton** [comment]
@Rahix can you check and let me know if the pin I chose make sense?

**Review by Rahix — APPROVED** [review]
Looks good, thank you very much!

**Pull request merged**
