### PR TITLE
ravedude documentation

### PR DESCRIPTION
**Pull request by michelepagot**
Mention in the ravedude documentation what is a suitable avrdude versioin to be used (6.3)

### CODE REVIEW

**Comment by Rahix** [comment]
Hi, thanks for the PR.

Instead of just documenting this in some README, I think it would be much better to have `ravedude` actually verify what version of `avrdude` is installed by calling `avrdude -?` and parsing the version string.  If the version is unsupported, it should bail out instead of letting people run into the issues.  This is going reach people much more likely than if we just have a small note in the README.

Would you be interested in implementing that?

**Comment by luukvanderduim** [comment]
> 
> Would you be interested in implementing that?

I would!  If you and @michelepagot don't object, that is. ;)
Is there a minimum version that we know of or is the idea to declare 6.3> because it is known to work fine?
Thanks in advance!

**Comment by Rahix** [comment]
@luukvanderduim, that's awesome, please go for it!

>  Is there a minimum version that we know of or is the idea to declare 6.3> because it is known to work fine?

Yeah, let's not try to deal with older versions, it's enough of a mess as it stands.  avrdude 6.3 was released 2016 so I'd say there is no excuse for using older version in 2021.

Thanks for picking this up! :)

**Comment by stappersg** [comment]
On Mon, Sep 13, 2021 at 08:05:08AM -0700, Luuk van der Duim wrote:
> > 
> > Would you be interested in implementing that?
> 
> I would!  If you and @michelepagot don't object, that is. ;)

Sent patches     :-)


> Is there a minimum version that we know of
> or is the idea to declare 6.3> because it is known to work fine?

Put minimum version in a variable, constant or other data structure
that enables future maintenance. Yes, sent patches ...


Regards Stappers

P.S.
It is not important what my opinion is on ravedude checking
which avrdude version is being used.

Important is there is software with 100 freedoms
001 freedom to use
010 freedom to share
011 freedom to study
100 freedom to modify

**Comment by Rahix** [comment]
Closing as this is now superseded by #211.  Thanks @michelepagot for kicking off this topic.

**Comment by luukvanderduim** [comment]
> Closing as this is now superseded by #211. Thanks @michelepagot for kicking off this topic.

Is it possible you meant #221, or am I missing something?

**Comment by Rahix** [comment]
Of course, sorry!

**Pull request closed without merging**
