### PR TITLE
Add digispark kickstarter Attiny85 board and cleanup CI

### PR DESCRIPTION
**Pull request by simonsso**
* Add digispark kickstarter Attiny85 board Digispark board is almost same as trinket, but all 6 GPIO are accessible
* Update workflows Remove unmaintained actions-rs
* Chore: silence warnings
   CI builds with warnings are errors, all existing warnings were either solved or silenced.

### CODE REVIEW

**Comment by simonsso** [comment]
This is the same as #367 but I have also cleaned up CI jobs.

**Comment by Rahix** [comment]
Hi, thanks a lot for the PR!  I've taken the liberty to already apply the CI changes + warning fixes in commits f1010cf16d94 ("treewide: Fix warnings") and 1ab563c8c9af ("ci: Update workflows").  For the board, I'm not sure how we should proceed, did you notice any notable differences between yours and the other PR?  I'll also take another look in the coming days.

**Comment by simonsso** [comment]
@Rahix  the other had better comments than my code for the registers but they were more or less identical.

**Comment by simonsso** [comment]
Since the changes are made and merge we can just close this PR now.

Thanks

**Pull request closed without merging**
