### PR TITLE
generic: spi: Add method to reconfigure the peripheral

### PR DESCRIPTION
**Pull request by explicite**
Draft for #42

@Rahix can you please review if I made change in correct place? I will try to find some test case to prove this.

### CODE REVIEW

**Review by Rahix — COMMENTED** [review]
The code looks good to me, but you're right, we need a way to test this ...

**Comment by explicite** [comment]
Test case with two Arduino: Mega2560(**Master**), Uno(**Slave**). Master connected via UART to PC (**57600**). 
1. `char` from PC go Mega
2. Mega fwd. `char` to Uno via SPI
3. Uno echo `char` to Mega
4. Mega update  reconfigure SPI (serial clock rate)
5. Mega echo `char` to Uno
6. Uno echo `char` to Mega
7. Mega fwd `char` to PC

If received char will be same then test pass. Will review signals via logic analyzer between Uno and Mega

@Rahix should I change data order and mode to?

**Review by Rahix — APPROVED** [review]
I think this is good enough and would have caught any obvious problems.  Thanks a lot!

**Comment by explicite** [comment]
Looks like I'm not able to setup SPI to communicate between Arduino. I review with logic analyzer and I cannot get any output from Uno and Mega. @Rahix can you please review https://github.com/Rahix/avr-hal/pull/118

**Pull request merged**
