### PR TITLE
atmega-hal: Add support for ATmega1284P

### PR DESCRIPTION
**Pull request by icanwalkonwater**
Added support for the ATmega1284P by following [the datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/doc8059.pdf).

### CODE REVIEW

**Comment by Rahix** [comment]
Hi, thanks a lot for the PR!

Can you take a look at the CI failures?  It seems some other MCUs no longer build with your changes.

**Comment by icanwalkonwater** [comment]
It seems I forgot to add a `#[cfg]` somewhere, it should compile fine now.

**Review by Rahix — APPROVED** [review]
Changes look good, thanks!

I don't have the hardware so I'll have to rely on your testing.  How much did you verify this code on a real device?  Or is it just a blind implementation for now?  I think I'll merge the changes either way, but of course it would be nice to know that things have been proven to work ;)

**Comment by icanwalkonwater** [comment]
Thank you =)

I have the board, it is salvaged from an Anet A8 printer.
I only really needed the USART implementation, but it felt wrong to not do the other ones.

I tested the USART0 and LED and it does work, as for the other peripherals I might need the ADC at some point but since it is not a developement board, the pins arent't exposed making it hard to test with my non-existent equipement.

I was thinking of also adding it to the `arduino-hal` crate with the pins renamed [like this](https://github.com/ralf-e/ANET-3D-Board-V1.0/blob/master/ANET3D_Board_Schematic.png). It will make my life easier but that may not be the purpose of this crate (since its called arduino you know).

**Comment by Rahix** [comment]
Alright, good enough for me.  Let's not worry about the other pieces until someone tries using them.

> I was thinking of also adding it to the arduino-hal crate named something like anet3d with the pins renamed like this. It will make my life easier but that may not be the purpose of this crate (since its called arduino you know).

My suggestion would be that you create yourself a custom "board support crate" that essentially has the same structure as `arduino-hal` but only for your board.  This is the usual approach when working with custom hardware.

**Pull request merged**
