### PR TITLE
Support for ATMega32A

### PR DESCRIPTION
**Pull request by West14**
I implemented HAL support with this (Rahix/avr-device#123) PR to the avr-device repository, but I wasn't sure if I should publish it. I haven't tested all the features, but I think everything should be fine.

### CODE REVIEW

**Comment by Rahix** [comment]
Hey, please add your MCU to `.github/workflows/ci.yml` and rebase on latest `main` so CI runs for the MCU :)

**Comment by West14** [comment]
Uh, I hope I did it right.

**Comment by West14** [comment]
Rebased to latest master update.

**Review by Rahix — APPROVED** [review]
Thanks so much and sorry for the late reaction!

**Pull request merged**
